### ISSUE TITLE
[TASK] List of web fixes

### ISSUE THREAD

**Issue by Tinashe-Austin** [COS301-SE-2024/Office-Capacity-Predictor#420]
**Task Request**

- [ ] Make sure light theme color is proper ie change colours and figure out which colours work
- [ ] fix employee page error, ie page loading with no info, consider making a clearer error message
- [ ] fix graphs layout inclusive of adding infographics to all graphs, date selectors, reorganising worker dashboard
- [ ] rename sidenav to clearer labels
- [ ] employees page remove misleading clicking and add more insightful icons
- [ ] make bookings page less boring
- [ ] the rest of everything

<@Tinashe-Austin>, please tick off as you complete each task by clicking on the task you are done with in this comment

**Additional info**
Any additional info, articles that you think may help the developer should be added here.
